# Generated by Django 3.0.6 on 2020-08-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songFile',
            field=models.FileField(blank=True, upload_to='home/music'),
        ),
    ]
